name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonbabenko/pre-commit-terraform:latest
      volumes:
        - ${{ github.workspace }}:/lint
    steps:
      - name: Run pre-commit
        run: |
          ls -lh
          pre-commit run -a
